environment_variables: {}
external_package_dirs: []
model_metadata:
  example_model_input: {"prompt": "What is the meaning of life?"}
model_name: Mistral 7B
python_version: py311
requirements:
- transformers==4.38.2
- sentencepiece==0.1.99
- accelerate==0.23.0
- torch==2.2.2
- datasets==2.18.0
- deepspeed==0.14.0
- fire==0.6.0
- matplotlib==3.8.3
- numpy==1.26.4
- pandas==2.2.1
- peft==0.10.0
- scikit_learn==1.4.1.post1
- seaborn==0.13.2
- sentence_transformers==2.6.1
- setuptools==65.5.0

resources:
  accelerator: A10G
  use_gpu: true
secrets: {}
system_packages: []